[package]
name = "indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
pulldown-cmark = "0.11.3"
regex = "1"
lazy_static = "1.5.0"
